name: Create issue for Dependabot PR
on:
  pull_request:
    types: [opened, reopened]

jobs:
  issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      repository-projects: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Step 1 -> Code Checkout
        uses: actions/checkout@v3
      - name: Step 2 -> Create issue if Dependabot PR
        if: github.event.pull_request.user.login  == 'dependabot[bot]'
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_URL: ${{ github.event.pull_request.url }}
        run: |
          title="Dependabot PR  - $PR_TITLE opened"
          body="The below issue is created as Dependabot has opened PR #$PR_NUMBER
          Link: $PR_URL
          Please review and merge the PR as per the review guidelines."
          gh issue create --title "$title" --body "$body" --assignee "${{ github.repository_owner }}"
