name: Auto Merge Dependabot PR
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      repository-projects: write
      pull-requests: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Step 1 -> Code Checkout
        uses: actions/checkout@v3
      - name: Step 2 -> Approve the PR if created by Dependabot
        # if: github.event.pull_request.user.login  == 'dependabot[bot]'
        run: gh pr review 1 --approve       
      - name: Step 3 -> Merge the PR if created by Dependabot
        # if: github.event.pull_request.user.login  == 'dependabot[bot]'
        run:  gh pr merge 1 -d -r
